### ISSUE TITLE
Release version-1

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/tableschema-php#2]
# Description

This issue describes the set of tasks to complete in order to finish up work on the library.

# Tasks

- [x] Touch base with the @jobarratt and @pwalsh to notify that you consider the work complete
- [x] Provide a short description / link to code for how each action is implemented, with a link to unit tests that prove each action
- [x] Tag your candidate code as v0.1
- [x] Setup travis to auto deploy tagged versions to the package management solution for your language
- [ ] Ensure that the OKI account on the package management platform is an administrator/maintainer of the package, along with yourself
- [ ] Receive code review from @pwalsh and address any remaining issues
- [ ] Publish final version

**Comment by OriHoch** [comment]
@jobarratt and @pwalsh  - touching base and notifying you that I consider the work complete

[README](https://github.com/frictionlessdata/tableschema-php/blob/master/README.md) contains a summary of available actions and usage.

Unit tests are in [tests](https://github.com/frictionlessdata/tableschema-php/tree/master/tests) directory, with self-explanatory names.

final code is release on github ([v0.1.6](https://github.com/frictionlessdata/tableschema-php/releases)) and published to packagist: https://packagist.org/packages/frictionlessdata/tableschema

what's your username in packagist? is it `oki`?

**Comment by OriHoch** [comment]
@pwalsh please give me admin access to this repo - tableschema-php (so I can setup auto tagging of release in packagist)

**Comment by pwalsh** [comment]
done @OriHoch

**Comment by OriHoch** [comment]
setup the packagist github hook - so packagist is updated automatically on every github release

**Comment by roll** [comment]
Hi @OriHoch WDYT about releasing version 1 of the lib?

I developed recommendations to the FD software maintenance and the current state of the PHP libs (tableschema/datapackage) meets the criteria of being released as version 1.  

It's more about the development cycle rather than functionality:
- the active stage/iteration of development if over
- there are active users of the libraries
- we accept fix and small improvements

Just to communicate to users that we're in the stable state of things I'd recommend releasing version 1 of both libraries.

WDYT?

**Comment by roll** [comment]
I have created a status page for all our implementations - https://github.com/frictionlessdata/software/blob/master/STATUS.md - we have around 30 core libraries which all are in maintenance mode now (no active development of new features). So the goal is to mark all of them (when possible) as v1

**Comment by courtney-miles** [comment]
Once #43 and #42 have been completed I was intending to tag version 0.2.0.

Let me know if we would prefer it tagged 1.0.0 (I'm not clear if anything additional is first needed.)

**Comment by lwinfree** [comment]
thanks @courtney-miles!
@roll do you have thoughts about tagging it 0.2.0 vs 1.0.0?

**Comment by lwinfree** [comment]
Hi @courtney-miles! We're finally circling back to this (sorry for taking so long!). Would you be able to willing to release this as 1.0.0?

**Comment by DiegoPino** [comment]
@courtney-miles hi! I'm planning on moving https://github.com/frictionlessdata/datapackage-php to version v1.0.0 and would love to use your v1.0.0 version too. But since both projects are a bit offset in terms of composer dependencies, do you want me try to make a pull to change libraries, how tests are run, PHPs versions that are supported and include the GitHub Actions CI approach I added today? let me know, please feel free to give https://github.com/frictionlessdata/datapackage-php a look in case there is something there that does not apply/feel save in this repo. Thanks!

**Comment by DiegoPino** [comment]
@frictionlessdata/php @roll @lwinfree any updates on this? I'm in need of a 1.0.0 version of this so datapackage-php can use the right version in its composer.json. Since the dependency is only in this directly its our only blocker for a release. Do you want me to make the corresponding pulls here? I do not want to overstep but also do not want to make people wait too long. Hugs!

**Comment by courtney-miles** [comment]
Hey @DiegoPino

I am fine with tagging this as version 1.0.0, but it sounds like you need more than just a stable version numbers.

> But since both projects are a bit offset in terms of composer dependencies

Which dependencies are an issue for your project?

**Comment by DiegoPino** [comment]
Thanks @courtney-miles, tagging with v1.0.0 /doing the release so` packagist` exposes the right version is enough, and in terms of runtime library dependencies we are ok. Tests are passing now and CI too so its just a semantic thing.

My `offset` concern (silly one sorry) in more on the housekeeping side of things, on how phpunit and phpcs (and their versions) are run differently + GitHub actions v/s Travis thing, my feeling was into normalization across languages to give contributors a similar experience ? But it is totally ok that both repos follow their own paths. We will cover PHP 8.0 in the next release and then things may need a revision again.

I appreciate your time!

**Comment by courtney-miles** [comment]
I have released v1.0.0 -- sorry for the delay.

**Comment by roll** [comment]
Thanks @courtney-miles !
