### ISSUE TITLE
[disussion / decision] drop support for PHP 5.X

### ISSUE THREAD

**Issue by OriHoch** [frictionlessdata/tableschema-php#39]
see [PHP supported vesions](https://www.php.net/supported-versions.php) - PHP < 7 is not supported anymore.

[This PR](https://github.com/frictionlessdata/tableschema-php/pull/38) introduced a change which is not supported in PHP 5.6

Should we officially drop support for PHP < 7 ?

**Comment by courtney-miles** [comment]
Where version 0.1.9 will continue to exist for those still on PHP 5, I would vote towards dropping support for PHP 5.

In terms of what this means to drop support, I would suggest that this means that there are no revisions that change the interfaces in a way that breaks BC.  Where tableschema hasn't been updated since Nov 2017, it is unlikely that there will be a sudden need to change the interfaces for PHP 5.

So if a bug were found, and it could be corrected without changing the interfaces, then a branch from the `v0.1.9` tag could be created to allow a revision that would be tagged `v0.1.10`.

The `master` branch would become v0.2.0 (or v1.0.0 if you want to bite the bullet.)

As long authors specify PHP 5 in their `composer.json` file, I believe they will continue to get 0.1.x revisions and not 0.2.x revisions, regardless of the version specifier for frictionlessdata/tableschema.

**Comment by courtney-miles** [comment]
Support for PHP 5.6 and 7.0 has been removed.
